# Jaromir's keyboard
# Motivation / requirements:
# - stagger and thumkeys like Kyria
# - monoblock, Fn and arrow kayes like X-Bows
# - for ergo beginners => with num row like normal keyboard
units:
  # Constants
  choc_cap_x: 17.5
  choc_cap_y: 16.5
 
  choc_plate_thickness: 1.2
  mx_plate_thickness: 1.5
 
  # Parameters
  kx: U
  ky: U
  plate_thickness: mx_plate_thickness
  rotation: 18 # the angle between the left and right side is double this value
points:
  zones:
    matrix:
      columns:
        outer:
        pinky:
          key.stagger: 0.2ky
        ring:
          key.stagger: 0.7ky
        middle:
          key.stagger: 0.4ky
        index:
          key.stagger: -0.4ky
        inner:
          key.stagger: -0.2ky
      rows:
        mod:
        bottom:
        home:
        top:
        num:
    thumb:
      anchor:
        ref: matrix_inner_mod
        shift: [1.05kx, -7]
      columns:
        x:
          key.splay: -30
      rows:
        x:
    func:
      key.asym: left
      anchor:
        ref: matrix_outer_num
        shift: [-1.72kx, 0.9ky] # Ensure: Gap between F6 and F7 is centered. This is done by modifying 1st parameter.
        rotate: rotation
      columns:
        esc:
        f1:
          key.spread: 1.2kx
        f2:
        f3:
        f4:
        f5:
          key.spread: 1.2kx
        f6:
        f7:
        f8:
        f9:
          key.spread: 1.2kx
        f10:
        f11:
        f12:
    nav:
      key.asym: left
      anchor:
        ref: func_f12
        # Design: top row is aligned with Fn row
        # Ensure: Bottom row is aligned with "right matrix_outer_mod". This is done by modifying func.anchor.shift 2nd parameter
        shift: [2.0kx, -5ky]
      columns:
        left:
          rows:
            home:
              width: 1.95kx
              shift: [0.5kx, 0]
            top:
              shift: [-0.5kx, 0]
        middle:
          rows:
            num:
              width: 1.95kx
              shift: [0.5kx, 0]
            fn:
              shift: [-0.5kx, 0]
          rows.home.skip: true
        right:
          rows.num.skip: true
      rows:
        mod:
        bottom:
        home:
        top:
        num:
        fn:
    extra_left:
      key.asym: left
      anchor:
        ref: func_esc
        shift: [0, -2*ky]
      columns:
        x:
      rows:
        x:
        y:
    extra_right:
      key.asym: left
      anchor:
        ref: func_f12
        shift: [kx, -1.5*ky] # Remember _usb_c_cutout
      columns:
        x:
      rows:
        x:
        y:
    extra_center_sym:
      anchor:
        ref: matrix_inner_bottom
        shift: [kx, -0.1*ky]
      columns:
        x:
      rows:
        x:
    extra_center_asym:
      key.asym: left
      anchor:
        ref: func_f6
        shift: [0.5*kx, -4.4*ky] # TODO calclulate position exactly
      columns:
        x:
      rows:
        x:
  rotate: -rotation
  mirror:
    ref: matrix_inner_home
    distance: 46
outlines:
  outline:
    - what: polygon
      operation: stack
      points:
        - ref: func_esc
          shift: [-0.5kx, 0.5ky]
        - ref: func_esc
          shift: [-0.5kx, -5.5ky]
#        - ref: matrix_outer_mod
#          shift: [-kx, -ky]
        - ref: thumb_x_x
          shift: [0.4kx, -0.4ky]
        - ref: mirror_thumb_x_x
          shift: [0.4kx, -0.4ky]
#        - ref: mirror_matrix_outer_mod
#          shift: [kx, -ky]
        - ref: nav_right_mod
          shift: [-2.3kx, -0.5ky]
        - ref: nav_right_mod
          shift: [0.5kx, -0.5ky]
        - ref: nav_right_fn
          shift: [0.5kx, 0.5ky]
  _bottom_arch_circle_left:
    - what: circle
      radius: 150
      where:
        ref: matrix_outer_mod
        shift: [66, -150]
  _bottom_arch_circle_right:
    - what: circle
      radius: 150
      where:
        ref: mirror_matrix_outer_mod
        shift: [66, -150]
  _main: [
      +outline,
      #-_bottom_arch_circle_left,
      #-_bottom_arch_circle_right # Bug in Ergogen - the case is not generated when using this circle
  ]
  _fillet:
    - what: outline
      name: _main
      fillet: 6
  _usb_c_cutout:
    - what: rectangle
      size: [9.28, 6.67] # Probably standard size of USB C
      where:
        ref: func_f12
        shift: [1kx, 0.35ky]
  combined: [
      _fillet,
      -_usb_c_cutout
  ]
  _switch_cutouts:
    - what: rectangle
      where: true
      asym: source
      size: 14 # Plate cutouts are 14mm * 14mm for both MX and Choc
      bound: false
  switch_plate:
    [ combined, -_switch_cutouts]
cases:
  switchplate:
    - what: outline
      name: switch_plate
      extrude: plate_thickness
      shift: [-85, -40, 0]
  bottom:
    - what: outline
      name: combined
      extrude: plate_thickness
      shift: [-85, -40, 0]
 